### ISSUE TITLE
Simple path style returns undefined for a plain string value

### ISSUE THREAD

**Issue by mikestead** [Himenon/openapi-parameter-formatter#4]
A path parameter of style `simple` (default) is returning `undefined` for a plain string. Seems it [only allows for an array](https://github.com/Himenon/openapi-parameter-formatter/blob/41ea27dd955c884735ef1c6844e02b9324cbfff1/src/Core.ts#L12).

I can see why this one is a bit confusing in [the spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#style-values), as it states `simple` is type `array`.

However you can see in both the [rfc6570 spec](https://tools.ietf.org/html/rfc6570#section-3.2.2) it references and the [examples](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#style-examples), that it supports individual strings and objects.

Thanks for the library.

**Comment by Himenon** [comment]
Thanks for making the issue. I will check the contents.
